model:
  # learning_rate: 0.0001
  base_learning_rate: 4.5e-06
  min_learning_rate: 0.0
  target: models.stage1_masked.mqvae.MaskedVectorQuantizationModel
  params:
    encoder_config:
      target: modules.diffusionmodules.model.Encoder
      params:
        double_z: false
        z_channels: 256
        resolution: 256
        in_channels: 3
        out_ch: 3
        ch: 128
        ch_mult: [1, 1, 2, 2]
        num_res_blocks: 2
        attn_resolutions: [32]
        dropout: 0.0
    decoder_config:
      target: modules.masked_quantization.decoder.Decoder
      params:
        ch: 128
        in_ch: 256
        out_ch: 3
        ch_mult: [1, 1, 2, 2]
        num_res_blocks: 2
        resolution: 256
        attn_resolutions: [32]
        dropout: 0.0
        resamp_with_conv: true
        give_pre_end: false
    masker_config:
      target: modules.masked_quantization.masker_vanilla_refine.VanillaMasker
      params:
        topk_ratio: 0.30
        input_token_num: 1024
        input_dim: 256
        patch_size: 8
        score_pred_net_mode: 2layer
        codebook_dim: 256
    demasker_config:
      target: modules.masked_quantization.demasker_vanilla.VanillaDemasker
      params:
        output_dim: 256
        codebook_dim: 256
        height_and_width: 32
        n_layer: 8
        mask_init_value: 0.02
    lossconfig:
      target: modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: false
        disc_in_channels: 3
        disc_start: 0
        disc_weight: 0.75
        codebook_weight: 1.0
        disc_weight_max: 1.0
    vqconfig:
      target: modules.vector_quantization.quantize2.VectorQuantize2
      params:
        codebook_size: 1024
        codebook_dim: 256
        channel_last: false
        accept_image_fmap: false
        commitment_beta: 0.25
        decay: 0.99
        restart_unused_codes: true
        commit_loss_legacy: true
    image_key: image
    monitor: val_rec_loss
    warmup_epochs: 0.1
    scheduler_type: linear-warmup_cosine-decay

data:
  target: data.build.DataModuleFromConfig
  params:
    batch_size: 16 # 30
    num_workers: 8
    train:
      target: data.imagenet.ImageNetTrain
      params:
        config:
          is_eval: False
          size: 256
    validation:
      target: data.imagenet.ImageNetValidation
      params:
        config:
          is_eval: True
          size: 256